/*
 * AD4111 Analog to Digital Converter (ADC) Driver
 *
 * Author: Love Mitteregger
 * Created: 10 jun 2024
 *
 */

// General libraries
#include <math.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

// Zephyr libraries
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/device.h>
#include <zephyr/drivers/spi.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/linker/devicetree_regions.h>
// #include <zephyr/ztest.h> // Zephyrs Testing Framework, must also be enabled in prj.conf if used

// AESIR libraries
#include "ad4111.h"
// Placeholder

// Set logging system to capture any log messages generated by the code
LOG_MODULE_REGISTER(ad4111, CONFIG_SENSOR_LOG_LEVEL);

/* REMEMBER: DRIVER FUNCTIONS SHOULD BE DESIGNED TO OPERATE INDEPENDENTLY OF THE NUMBER OF DEVICES USING THEM. */
/* Typedef declarations functioning as aliases to their specific function pointer */
typedef int (*adc_init_t) (const struct device *dev);
typedef int (*adc_reset_t) (const struct device *dev);
typedef int (*adc_config_channel_t) (const struct device *dev);
typedef int (*adc_write_register_t) (const struct device *dev);
typedef int (*adc_read_register_t) (const struct device *dev);
typedef int (*adc_read_data_t) (const struct device *dev);
typedef void (*adc_config_irq_t) (const struct device *dev);
typedef void (*adc_isr_t) (const struct device *dev);

/* A structure that functions as a device independent subsystem API, applications will be able to program to this generic API */
struct adc_api{
    adc_init_t do_a;            // Initialize ADC
    adc_reset_t do_b;           // Reset ADC
    adc_config_channel_t do_f;  // Enable/Disable ADC channels
    adc_write_register_t do_c;  // Write to ADC register
    adc_read_register_t do_d;   // Read from ADC register
    adc_read_data_t do_e;       // Read from ADC data register
    adc_isr_t do_isr;           // Handle ADC interrupt service routine
};

struct adc_config{
    DEVICE_MMIO_ROM;
    adc_config_irq_t config_func;
};

void adc_isr(const struct device *dev) {}

int adc_init(const struct device *dev) {}

// Function for resetting the ADCs
// Returning CS' high sets the digital interface to the default state and halts any serial interface operation.