# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: surtr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsurtr.proto\x12\x07surtrpb\"*\n\rSwitchControl\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\x08\"0\n\x0eStepperControl\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nmotorDelta\x18\x02 \x01(\x11\"\x94\x01\n\x0cSwitchStates\x12\x0b\n\x03sw1\x18\x01 \x01(\x08\x12\x0b\n\x03sw2\x18\x02 \x01(\x08\x12\x0b\n\x03sw3\x18\x03 \x01(\x08\x12\x0b\n\x03sw4\x18\x04 \x01(\x08\x12\x0b\n\x03sw5\x18\x05 \x01(\x08\x12\x0b\n\x03sw6\x18\x06 \x01(\x08\x12\x0b\n\x03sw7\x18\x07 \x01(\x08\x12\x0b\n\x03sw8\x18\x08 \x01(\x08\x12\r\n\x05step1\x18\t \x01(\x05\x12\r\n\x05step2\x18\n \x01(\x05\"\xdf\x01\n\x0f\x41\x44\x43Measurements\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06value0\x18\x02 \x01(\x05\x12\x0e\n\x06value1\x18\x03 \x01(\x05\x12\x0e\n\x06value2\x18\x04 \x01(\x05\x12\x0e\n\x06value3\x18\x05 \x01(\x05\x12\x0e\n\x06value4\x18\x06 \x01(\x05\x12\x0e\n\x06value5\x18\x07 \x01(\x05\x12\x0e\n\x06value6\x18\x08 \x01(\x05\x12\x0e\n\x06value7\x18\t \x01(\x05\x12\x0e\n\x06value8\x18\n \x01(\x05\x12\x0e\n\x06value9\x18\x0b \x01(\x05\x12\x0f\n\x07value10\x18\x0c \x01(\x05\x12\x0f\n\x07value11\x18\r \x01(\x05\"\x1c\n\x08Ignition\x12\x10\n\x08password\x18\x01 \x01(\x05\"\xad\x02\n\x0cSurtrMessage\x12\x1a\n\rus_since_boot\x18\x01 \x01(\x03H\x01\x88\x01\x01\x12)\n\x07sw_ctrl\x18\x02 \x01(\x0b\x32\x16.surtrpb.SwitchControlH\x00\x12,\n\tstep_ctrl\x18\x03 \x01(\x0b\x32\x17.surtrpb.StepperControlH\x00\x12\x34\n\x10\x61\x64\x63_measurements\x18\x04 \x01(\x0b\x32\x18.surtrpb.ADCMeasurementsH\x00\x12%\n\x08ignition\x18\x05 \x01(\x0b\x32\x11.surtrpb.IgnitionH\x00\x12.\n\rswitch_states\x18\x06 \x01(\x0b\x32\x15.surtrpb.SwitchStatesH\x00\x42\t\n\x07\x63ommandB\x10\n\x0e_us_since_bootb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'surtr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SWITCHCONTROL._serialized_start=24
  _SWITCHCONTROL._serialized_end=66
  _STEPPERCONTROL._serialized_start=68
  _STEPPERCONTROL._serialized_end=116
  _SWITCHSTATES._serialized_start=119
  _SWITCHSTATES._serialized_end=267
  _ADCMEASUREMENTS._serialized_start=270
  _ADCMEASUREMENTS._serialized_end=493
  _IGNITION._serialized_start=495
  _IGNITION._serialized_end=523
  _SURTRMESSAGE._serialized_start=526
  _SURTRMESSAGE._serialized_end=827
# @@protoc_insertion_point(module_scope)
